#APP ----------------------------------------------------------------------------------------------
version: '1.0'
services:
  app:
    container_name: mentalbot-app
    build:
      context: ./
    links:
      - mongo
      - vault
    ports:
      - "8094:8094"
    depends_on:
      - mongo
      - vault

#MONGO ----------------------------------------------------------------------------------------------
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - '27018:27017'
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGODB_HOST=$${spring.data.mongodb.host}
      - MONGODB_PORT=$${spring.data.mongodb.port}
      - MONGODB_DATABASE=$${spring.data.mongodb.database}
      - MONGODB_USERNAME=$${spring.data.mongodb.username}
      - MONGODB_PASSWORD=$${spring.data.mongodb.password}

#VAULT ----------------------------------------------------------------------------------------------
  vault:
    image: vault:1.2.1
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    build: ./
    env_file:
      - .env
    command: vault server -dev -dev-root-token-id=$VAULT_ROOT_TOKEN  -dev-listen-address=$VAULT_LISTEN_ADDRESS