#APP ----------------------------------------------------------------------------------------------
version: '1.0'
services:
  app:
    container_name: mentalbot-app
    build:
      context: ./
    links:
      - mongo
      - vault
    ports:
      - "8094:8094"
    depends_on:
      - mongo
      - vault

#MONGO ----------------------------------------------------------------------------------------------
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - '27018:27017'
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGODB_HOST=$${spring.data.mongodb.host}
      - MONGODB_PORT=$${spring.data.mongodb.port}
      - MONGODB_DATABASE=$${spring.data.mongodb.database}
      - MONGODB_USERNAME=$${spring.data.mongodb.username}
      - MONGODB_PASSWORD=$${spring.data.mongodb.password}

#VAULT ----------------------------------------------------------------------------------------------
  vault:
    image: vault:1.6.1
    container_name: vault
    command: ["sh", "-c", "vault server -config /vault/config/config.hcl"]
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    volumes:
      - ./vault/config.hcl:/vault/config/config.hcl

  vault-init:
    image: vault:1.6.1
    container_name: vault-init
    depends_on:
      - vault
    volumes:
      - ./vault/init-vault.sh:/vault/scripts/init-vault.sh
      - ./vault/keys:/vault/keys
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_DEV_ROOT_TOKEN_ID: root
    command: [ "sh", "-c", "/vault/scripts/init-vault.sh" ]

