#APP ----------------------------------------------------------------------------------------------
version: '1.0'
services:
  app:
    build: .
    links:
      - mongo
    ports:
      - "8094:8095"
    container_name: mentalbot-app
    depends_on:
      - mongo

#MONGO ----------------------------------------------------------------------------------------------
  mongo:
    ports:
      - '27018:27017'
    container_name: mongo-db
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGODB_HOST=$${spring.data.mongodb.host}
      - MONGODB_PORT=$${spring.data.mongodb.port}
      - MONGODB_DATABASE=$${spring.data.mongodb.database}
      - MONGODB_USERNAME=$${spring.data.mongodb.username}
      - MONGODB_PASSWORD=$${spring.data.mongodb.password}
    image: mongo

